services:
  sakila_cl_local:
    image: mysql:9
    restart: always
    environment:
      MYSQL_DATABASE: 'sakila'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'yolo'
      MYSQL_ROOT_PASSWORD: 'yolo'
    ports:
      - '3310:3306'
    expose:
      - '3310'
    volumes:
      - sakila_cl_local_st_10:/var/lib/mysql

volumes:
  sakila_cl_local_st_10:
